"""
Build a Windows executable for Omni-ML-GUI using PyInstaller.

Usage examples (run on Windows):
  python scripts/build_windows_exe.py --mode fast
  python scripts/build_windows_exe.py --mode single
"""

from __future__ import annotations

import argparse
import json
import platform
import shutil
import subprocess
import sys
from pathlib import Path


def _load_build_meta(root: Path) -> dict[str, str]:
    meta_path = root / "build_meta.json"
    if not meta_path.exists():
        raise FileNotFoundError(f"Missing build metadata file: {meta_path}")
    with open(meta_path, "r", encoding="utf-8") as fh:
        meta = json.load(fh) or {}

    required = ("app_name", "exe_name", "version", "publisher", "url", "copyright", "description")
    missing = [k for k in required if not str(meta.get(k, "")).strip()]
    if missing:
        raise ValueError(f"build_meta.json is missing required keys: {', '.join(missing)}")
    return {k: str(v).strip() for k, v in meta.items()}


def _version_to_tuple(version: str) -> tuple[int, int, int, int]:
    parts = [p for p in str(version).strip().split(".") if p != ""]
    nums: list[int] = []
    for p in parts[:4]:
        nums.append(int(p))
    while len(nums) < 4:
        nums.append(0)
    return tuple(nums)  # type: ignore[return-value]


def _write_windows_version_info(root: Path, meta: dict[str, str]) -> Path:
    version_tuple = _version_to_tuple(meta["version"])
    version_str = ".".join(str(x) for x in version_tuple)
    version_file = root / "installer" / "windows_version_info.txt"
    payload = f"""# UTF-8
#
# Auto-generated by scripts/build_windows_exe.py from build_meta.json
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
    ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        "040904B0",
        [StringStruct("CompanyName", "{meta['publisher']}"),
        StringStruct("FileDescription", "{meta['description']}"),
        StringStruct("FileVersion", "{version_str}"),
        StringStruct("InternalName", "{meta['exe_name']}"),
        StringStruct("LegalCopyright", "{meta['copyright']}"),
        StringStruct("OriginalFilename", "{meta['exe_name']}.exe"),
        StringStruct("ProductName", "{meta['app_name']}"),
        StringStruct("ProductVersion", "{version_str}")])
      ]),
    VarFileInfo([VarStruct("Translation", [1033, 1200])])
  ]
)
"""
    version_file.write_text(payload, encoding="utf-8")
    return version_file


def _run(cmd: list[str], cwd: Path) -> None:
    print(">", " ".join(cmd))
    subprocess.run(cmd, cwd=str(cwd), check=True)


def _build_fast(root: Path) -> None:
    _run(
        [
            sys.executable,
            "-m",
            "PyInstaller",
            "--noconfirm",
            "--clean",
            str(root / "omni_ml_gui_fast.spec"),
        ],
        cwd=root,
    )


def _build_single_file(root: Path, use_upx: bool, meta: dict[str, str], version_file: Path) -> None:
    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        "--onefile",
        "--windowed",
        "--name",
        meta["exe_name"],
        "--optimize",
        "2",
        "--strip",
        "--hidden-import",
        "shiboken6",
        "--hidden-import",
        "PySide6.QtSvg",
        "--hidden-import",
        "PySide6.QtOpenGLWidgets",
        "--collect-submodules",
        "sklearn",
        "--add-data",
        f"{root / 'locales'};locales",
        "--add-data",
        f"{root / 'interface' / 'style'};interface/style",
        "--exclude-module",
        "tkinter",
        "--exclude-module",
        "pytest",
        "--exclude-module",
        "IPython",
        "--exclude-module",
        "jupyter",
        "--exclude-module",
        "notebook",
        str(root / "run_gui.py"),
    ]

    mapping_json = root / "scripts" / "q1_social_science_mappings.json"
    if mapping_json.exists():
        cmd.extend(["--add-data", f"{mapping_json};scripts"])

    icon_path = root / "assets" / "app.ico"
    if icon_path.exists():
        cmd.extend(["--icon", str(icon_path)])

    if version_file.exists():
        cmd.extend(["--version-file", str(version_file)])

    if not use_upx:
        cmd.append("--noupx")

    _run(cmd, cwd=root)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build a lightweight Windows executable for Omni-ML-GUI."
    )
    parser.add_argument(
        "--mode",
        choices=("fast", "single"),
        default="fast",
        help="fast=onedir fastest startup, single=onefile smaller distribution unit",
    )
    parser.add_argument(
        "--upx",
        action="store_true",
        help="Use UPX compression when available (smaller exe, possibly slower startup).",
    )
    parser.add_argument(
        "--clean-output",
        action="store_true",
        help="Delete old build/ and dist/ folders before build.",
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    meta = _load_build_meta(root)
    version_file = _write_windows_version_info(root, meta)

    if platform.system().lower() != "windows":
        print(
            "Warning: .exe builds are only produced on Windows. "
            "Run this command on a Windows machine.",
            file=sys.stderr,
        )

    if args.clean_output:
        for folder_name in ("build", "dist"):
            folder = root / folder_name
            if folder.exists():
                shutil.rmtree(folder)
                print(f"Deleted {folder}")

    if args.mode == "fast":
        _build_fast(root)
    else:
        _build_single_file(root, use_upx=args.upx, meta=meta, version_file=version_file)

    print("\nBuild complete.")
    exe_file = f"{meta['exe_name']}.exe"
    if args.mode == "fast":
        print(f"Output: {root / 'dist' / meta['exe_name'] / exe_file}")
    else:
        print(f"Output: {root / 'dist' / exe_file}")


if __name__ == "__main__":
    main()
